(function(){const siteNavigation=document.getElementById('site-navigation');if(!siteNavigation){return}
const button=siteNavigation.getElementsByTagName('button')[0];if('undefined'===typeof button){return}
const menu=siteNavigation.getElementsByTagName('ul')[0];if('undefined'===typeof menu){button.style.display='none';return}
if(!menu.classList.contains('nav-menu')){menu.classList.add('nav-menu')}
button.addEventListener('click',function(){siteNavigation.classList.toggle('toggled');if(button.getAttribute('aria-expanded')==='true'){button.setAttribute('aria-expanded','false')}else{button.setAttribute('aria-expanded','true')}});document.addEventListener('click',function(event){const isClickInside=siteNavigation.contains(event.target);if(!isClickInside){siteNavigation.classList.remove('toggled');button.setAttribute('aria-expanded','false')}});const links=menu.getElementsByTagName('a');const linksWithChildren=menu.querySelectorAll('.menu-item-has-children > a, .page_item_has_children > a');for(const link of links){link.addEventListener('focus',toggleFocus,!0);link.addEventListener('blur',toggleFocus,!0)}
for(const link of linksWithChildren){link.addEventListener('touchstart',toggleFocus,!1)}
function toggleFocus(){if(event.type==='focus'||event.type==='blur'){let self=this;while(!self.classList.contains('nav-menu')){if('li'===self.tagName.toLowerCase()){self.classList.toggle('focus')}
self=self.parentNode}}
if(event.type==='touchstart'){const menuItem=this.parentNode;event.preventDefault();for(const link of menuItem.parentNode.children){if(menuItem!==link){link.classList.remove('focus')}}
menuItem.classList.toggle('focus')}}}());document.addEventListener("DOMContentLoaded",function(event){var userLang=navigator.language||navigator.userLanguage;userLang=userLang.split('-')[0];var pageLang=document.documentElement.lang.split('-')[0];var hreflangTags=document.querySelectorAll('link[rel="alternate"][hreflang]');var supportedLanguages=["tr","es","it","ar","de","ru","fr"];var langMessages={"tr":"Makaleyi Türkçe Oku >","es":"Lea el artículo en español >","it":"Leggi l'articolo in italiano >","ar":"اقرأ المقالة باللغة العربية >","de":"Lesen Sie den Artikel auf Deutsch >","ru":"Читать статью на русском >","fr":"Lire l'article en français >",};if(supportedLanguages.includes(userLang)&&userLang!==pageLang){hreflangTags.forEach(function(tag){var lang=tag.getAttribute('hreflang');if(lang===userLang){var langAlertElement=document.querySelector('.lang_alert');if(langAlertElement){var message=langMessages[userLang];var href=tag.getAttribute('href');langAlertElement.textContent=message;langAlertElement.href=href;langAlertElement.classList.add("visible")}}})}
$(document).ready(function(){var $body=$("body");var $mobileMenu=$("#mobile-menu");var $mobileToggleHolder=$(".mobile-toggle-holder");var $clickCapture=$(".click-capture");function toggleMobileMenu(){if($mobileMenu.hasClass("open")){$mobileMenu.removeClass("open");$body.removeClass("mm-open")}else{$mobileMenu.addClass("open");$body.addClass("mm-open")}}
$mobileToggleHolder.on("click",function(){toggleMobileMenu()});$clickCapture.add($mobileMenu.find(".thb-mobile-close")).on("click",function(){toggleMobileMenu()});$(document).on("keyup",function(event){if(event.keyCode===27&&$mobileMenu.hasClass("open")){toggleMobileMenu()}});$('.search_input').keyup(function(){clearTimeout($.data(this,'timer'));var wait=setTimeout(search,175);$(this).data('timer',wait)});function search(){$("#searchsubmit .loading").removeClass("displaynone");$("#searchsubmit .fontaw-search").addClass("displaynone");var a=$('.search_input').val(),b=$(".phoneresult");$(".phoneresult > li").remove();a.length?$.get(xiaomiui_navparams.backsearch,{term:a,lang:$('html').attr('lang').substr(0,2)}).done(function(a){b.html(a),$(".tid_search_result").removeClass("search_hide"),$("#searchsubmit .loading").addClass("displaynone"),$("#searchsubmit .fontaw-search").removeClass("displaynone")}):(b.empty(),$(".tid_search_result").addClass("search_hide"),$(".comparison-search").removeClass("anim"),$("#searchsubmit .loading").addClass("displaynone"),$("#searchsubmit .fontaw-search").removeClass("displaynone"))}
$(document).on("click",".phoneresult a",function(){}),document.addEventListener("click",function(a){a.target.closest(".tid_search_result, .search_input, #searchform")||$(".tid_search_result").addClass("search_hide"),$(".comparison-search").removeClass("anim")});$(".search_input").on("click",function(){if($(".search_input").val()!=""){$(".tid_search_result").removeClass("search_hide")}});var s=new class{constructor(e){const t=e&&e.time||"0.3s",a="true"===window.localStorage.getItem("darkmode"),s=window.matchMedia("(prefers-color-scheme: dark)").matches,i=null===window.localStorage.getItem("darkmode");(!0===a||i&&s)&&(document.body.classList.add("wp-night-mode-on"),$("#darkmo").toggleClass("active")),this.addStyle("\n      img, .darkmode-ignore {\n        isolation: isolate;\n        display: inline-block;\n      }\n    "),this.saveInCookies=!0,this.time=t}
addStyle(e){const t=document.createElement("link");t.setAttribute("rel","stylesheet"),t.setAttribute("type","text/css"),t.setAttribute("href","data:text/css;charset=UTF-8,"+encodeURIComponent(e)),document.head.appendChild(t)}
toggle(){const e=this.isActivated();document.body.classList.toggle("wp-night-mode-on"),$("#darkmo").toggleClass("active"),window.localStorage.setItem("darkmode",!e)}
isActivated(){return document.body.classList.contains("wp-night-mode-on")}};$("#darkmo").on("click",function(){s.toggle()});$(".bottom_fixad").after().on("click",function(){$(".bottom_fixad").css("display","none")});$(".searcherh").after().on("click",function(){$("form#searchform").toggleClass("active");$(".searcherh").toggleClass("active")})})})